server:
  port: 8080

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${POSTGRESQL_DATASOURCE_URL}
    username: ${POSTGRESQL_DATASOURCE_USERNAME}
    password: ${POSTGRESQL_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sprint.team2.monew: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true